### ISSUE TITLE
failed to bind cmake project

### ISSUE THREAD

**Issue by sammyne** [sbt/sbt-jni#109]
## Environment
- ubuntu 20.04
- cmake 3.16.3
- scala 2.12.15

## Problem
I have make native project based on CMake as [here](https://github.com/sammyne/mastering-scala3/tree/main/sbt-jni-cmake-quickstart). But it failed to build with `sbt core/run`, whose logs go as

```bash
(native / nativeCompile) No files were created during compilation, something went wrong with the CMake configuration.
```

Really appreciate if someone could help me out~

**Comment by pomadchin** [comment]
Hey @sammyne the project is slightly misconfigured, try to follow https://github.com/sbt/sbt-jni#canonical-use 

1. sbt configuration is a bit off
2. CMake file is in the incorrect location (probably your config is based on the cargo project)
3. CMake file is slightly off itself

Check out this diff https://github.com/sammyne/mastering-scala3/pull/1/files

**Comment by sammyne** [comment]
> https://github.com/sammyne/mastering-scala3/pull/1/files

The great PR works! @pomadchin 

And I find that adding `install(TARGETS helloworld LIBRARY DESTINATION .)` to the CMakeLists.txt of my old implementation also solves the problem.

But the [canonical-use](https://github.com/sbt/sbt-jni#canonical-use) guide failed me in case of
- sbt@1.6.2
- scala@2.12.15
- cmake@3.16.3

with error logs go as
```bash
[info] welcome to sbt 1.6.2 (Private Build Java 1.8.0_312)
[info] loading settings for project sbt-canonical-use-build from plugins.sbt ...
[info] loading project definition from /github.com/sammyne/mastering-scala3/sbt-canonical-use/project
/github.com/sammyne/mastering-scala3/sbt-canonical-use/build.sbt:9: error: value enablePlugin is not a member of sbt.File
possible cause: maybe a semicolon is missing before `value enablePlugin'?
    .enablePlugin(JniNative)
     ^
/github.com/sammyne/mastering-scala3/sbt-canonical-use/build.sbt:3: error: value dependsOn is not a member of sbt.File
possible cause: maybe a semicolon is missing before `value dependsOn'?
    .dependsOn(
     ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
```

**Comment by pomadchin** [comment]
Yes, there is indeed a typo, fixed it in terms ofhttps://github.com/sbt/sbt-jni/commit/b1bffd48d7d57e6431704720c5d6af937bc76db6

I'd also recommend you to check SBT docs to feel more comfortable with settings https://www.scala-sbt.org/
