### ISSUE TITLE
Cargo unexpected argument

### ISSUE THREAD

**Issue by SSTentacleSS** [sbt/sbt-jni#157]
Hello! Faced the problem that when using the cargo build system with Rust, it is not possible to use this configuration if the path contains spaces (cargo build /home/user/Desktop/Code Workspace/...)

**Comment by eed3si9n** [comment]
Probably a problem here - https://github.com/sbt/sbt-jni/blob/815096ba9b6a59a079c8236e2e0bc1040d55e6a1/plugin/src/main/scala/com/github/sbt/jni/build/Cargo.scala#L37-L40

**Comment by pomadchin** [comment]
Oh right, mb could be solved by just adding extra quotation around the path. I’m 🌴now but may assist in ~ a week+.

**Comment by pomadchin** [comment]
:D took me half a year to finish it
