### ISSUE TITLE
Cargo workspace

### ISSUE THREAD

**Issue by datben** [sbt/sbt-jni#185]
Hello, could you tell me how to configure sbt-jni with a cargo workspace and not a simple cargo lib, i did not find any example about this

**Comment by datben** [comment]
Ty @pomadchin , indeed my cargo.toml was miss configured, it seems to work now, ty for your time !

**Comment by datben** [comment]
I'll try to make one since i can't share the code

**Comment by datben** [comment]
@pomadchin could you try to compile this https://github.com/datben/jni-test ? this message should appear
[warn] More than one file was created during compilation, only the first one (/jni-test/jni-integration/target/native/x86_64-linux/bin/release/liba.so) will be used.

**Comment by pomadchin** [comment]
Oh that's a known limitation, we expect the underlying library to produce a single dylib. That's a good question what to do with multiple / how to handle it, so any suggestions and PRs are welcome. 

I believe all of the supported build tools have this limitation.

**Comment by pomadchin** [comment]
That's the origin of the message: https://github.com/sbt/sbt-jni/blob/main/plugin/src/main/scala/com/github/sbt/jni/build/Cargo.scala#L56-L62

**Comment by datben** [comment]
ok, so i guess the only solution is too split each crate for now

**Comment by pomadchin** [comment]
Or figure out what we really need to do [here](https://github.com/sbt/sbt-jni/blob/a2677b83734d7749a054a1c21324d4b61c95fb41/plugin/src/main/scala/com/github/sbt/jni/plugins/JniNative.scala#L117) in case of multiple libs present. 

Mb there is a room for improvement 🤔

**Comment by datben** [comment]
Is there a specific reason why 'lib' has to be 'File' and can't be 'List[File]'? i dont see where the output of nativeCompile is used
