### ISSUE TITLE
sbt-javah mangles names of @native methods in objects incorrectly

### ISSUE THREAD

**Issue by mrobakowski** [sbt/sbt-jni#36]
```scala
object Foo {
  @native def bar()
}
```
should generate
```cpp
JNIEXPORT void JNICALL Java_Foo_00024_bar
  (JNIEnv *, jobject);
```
but instead it generates
```cpp
JNIEXPORT void JNICALL Java_Foo___bar
  (JNIEnv *, jobject);
```

... at least on [recent JVMs](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/design.html#resolving-native-method-names). This seems to be already fixed in [gjavah](https://github.com/Glavo/gjavah/blob/568e70982ee0d574345cb5ae90ebd43ceaa090e8/src/main/java/org/glavo/javah/Utils.java#L49:26), but for some reason `$` is special-cased in here https://github.com/jodersky/sbt-jni/blob/fb2c301d550cee5491780b40b6e87b7e3fc73163/plugin/src/main/java/ch/jodersky/sbt/jni/javah/Utils.java#L55-L56

**Comment by jodersky** [comment]
Thanks for the pointers. I think that at the time I included gjavah in sbt-jni it didn't support special characters, so I just added the `$` case to replicate what `javah` generated in the past.

If you have a general fix however, I'd be happy to merge it

**Comment by mrobakowski** [comment]
In my case (I'm on JDK 14) the last branch of the if-else statement (`builder.append(String.format("_0%04x", (int) ch))`) produces the correct result. So just removing the special case for dollar sign would fix this. I'm not sure about other JDK versions though.

**Comment by pomadchin** [comment]
👋 could you check how the current main branch works for you? https://github.com/sbt/sbt-jni/pull/43 is merged so it could affect some things.

**Comment by jodersky** [comment]
FYI, I recently migrated gjavah to scala and fixed the issues with symbols. See here: https://github.com/jodersky/mill-jnilib/blob/master/jnilib/src/jnilib/gjavah.scala

I can confirm that it works, even with Scala 3 top-level functions and all sorts of funky characters.

**Comment by pomadchin** [comment]
@jodersky Thanks for confirming that! :tada:

sbt-jni snapshots live here now: https://oss.sonatype.org/content/repositories/snapshots/com/github/sbt/sbt-jni_2.12_1.0/ and should be easier to test to other folks. 

Let's close it for now, but @mrobakowski feel free to create a new issue and / or reopen this one.

**Comment by jodersky** [comment]
oh, I realize that my comment was ambiguous. When I said "it works", I meant that my `gjavah` scala port works. I can't speak for the updated official version.

Thanks for setting up maven publishing again!

**Comment by pomadchin** [comment]
Ooops! I'll reopen it again than :D

**Comment by pomadchin** [comment]
@mrobakowski btw, we can add the latest JDK into CI if it helps.

**Comment by mrobakowski** [comment]
Hi @pomadchin, sorry for not replying earlier.  I don't even remember what project I needed this for :sweat_smile:, so I cannot confirm or deny whether it works for my problem (I probably abandoned that side-project already). But the fix looks good, so thank you for that! :tada:
