### ISSUE TITLE
Scala 3 support 

### ISSUE THREAD

**Issue by pomadchin** [sbt/sbt-jni#45]
This issue is probably a bit obvious, but some one had to create it :D

In terms of API it means that macro annotations would have to be replaced (with a macro function call ?).

**Comment by kammoh** [comment]
But this is already dealt with in `build.sbt` and the master branch should be fully compatible with Scala 2.13.x. Are you referring to the latest published version by @jodersky? Until @jodersky finds the time to publish an updated version, I'd recommend you either try building from the source on master or use the version published on sonatype from my fork:
```
addSbtPlugin("xyz.kamyar" % "sbt-jni" % "1.4.3")

```
