### ISSUE TITLE
native library naming. 

### ISSUE THREAD

**Issue by harideva16** [sbt/sbt-jni#61]
Java native interface (jni) allows calling native libraries

 1. Windows --> .dll,
 2. Linux --> .so and
 3. Mac -->.dylib.

I use the following code to load native library.

      static {
        System.loadLibrary("mypl");
        }

If I generate native library in windows os the native library's name comes `mypl.dll`

But , in Linux os the native library's name comes `libmypl.so` and in mac it comes `libmypl.dylib` 

Will this code ` System.loadLibrary("mypl");` load native library correcty after creating JPackage  in linux and mac ?

**Comment by pomadchin** [comment]
Hey @harideva16, yes System.loadLibrary picks up windows dlls. But how is that connected to SBT-JNI? There is an outsdanding issue that tracks the Windows support https://github.com/sbt/sbt-jni/issues/20

**Comment by harideva16** [comment]
> Hey @harideva16, yes System.loadLibrary picks up windows dlls. But how is that connected to SBT-JNI? There is an outsdanding issue that tracks Windows support #20

Can you explain in detail ?

**Comment by pomadchin** [comment]
@harideva16 so this is a repo of the SBT JNI plugin; how is your question linked to the project?

**Comment by eed3si9n** [comment]
@harideva16 People are using GitHub issues to track bugs and todo list, often volunteering their time to main open source project. If you have general questions about how to use Java, please use Stackoverflow instead.
The entire point of sbt-jni is so you don't need to call `System.loadLibrary(...)`.
